

USE db_projeto --SELECIONE COM O MOUSE
--DEPOIS DE SELECIONAR, APERTE EM EXECUTAR ALI EM CIMA NO CANTO ESQUERDO

--DEPOIS, PODE SÓ APERTAR NOVAMENTE NO EXECUTAR 
-- E SER FELIZ =)

CREATE TABLE FORMAS_PAGAMENTO (
    ID_FORMA_PAGAMENTO INT IDENTITY PRIMARY KEY,
    FORMA_PAGAMENTO VARCHAR(200),
    VALOR DECIMAL(18,2), --VALORES MONETÁRIOS
    PIX VARCHAR(250),
    NUMERO_CARTAO VARCHAR(16),
    NOME_TITULAR VARCHAR(250),
    CVV CHAR(3),
    DATA_VENCIMENTO DATE
);

CREATE TABLE ONG (
    ID_ONG INT IDENTITY PRIMARY KEY,
    NOME_ONG VARCHAR(250),
    EMAIL VARCHAR(250),
    TELEFONE VARCHAR(20),
    CNPJ CHAR(14),
    RAZAO_SOCIAL VARCHAR(250),
    DESCRICAO VARCHAR(250),
    HISTORIA VARCHAR(250),
    SITE_URL VARCHAR(250),
    MISSAO VARCHAR(250),
    VISAO VARCHAR(250),
    VALORES VARCHAR(250),
    DATA_CADASTRO DATETIME,
    SENHA_ACESSO VARCHAR(50)
);

CREATE TABLE DOADOR (
    ID_DOADOR INT IDENTITY PRIMARY KEY,
    NOME VARCHAR(250),
    EMAIL VARCHAR(250),
    TELEFONE VARCHAR(15),
    DATA_NASCIMENTO DATE, 
    SENHA_LOGIN VARCHAR(250), -- Idealmente armazenar em hash
    DATA_CADASTRO DATETIME,
    SN_ATIVO BIT, -- BIT representa um booleano
    RUA VARCHAR(250),
    BAIRRO VARCHAR(250),
    CEP CHAR(8),
    NUMERO INT, 
    COMPLEMENTO VARCHAR(250),
    CIDADE VARCHAR(250),
    UF CHAR(2) --2 caracteres
);

CREATE TABLE PESSOA_JURIDICA (
    ID_PJURIDICA INT IDENTITY PRIMARY KEY,
    ID_DOADOR INT,
    CNPJ CHAR(14),
    RAZAO_SOCIAL VARCHAR(250),
    FOREIGN KEY (ID_DOADOR) REFERENCES DOADOR(ID_DOADOR)
);

CREATE TABLE PESSOA_FISICA (
    ID_PFISICA INT IDENTITY PRIMARY KEY,
    ID_DOADOR INT,
    CPF CHAR(11),
    SEXO VARCHAR(10),

    FOREIGN KEY (ID_DOADOR) REFERENCES DOADOR(ID_DOADOR)
);

CREATE TABLE DOACAO (
    ID_DOACAO INT IDENTITY PRIMARY KEY,
    ID_DOADOR INT, --FK
    DOACAO_ANONIMA BIT, 
    ID_FORMA_PAGAMENTO INT, --FK
    NOME_ITEM_DOADO VARCHAR(250),
    FOTO_ITEM_DOADO VARBINARY(MAX),
    DESCRICAO_ITEM_DOADO VARCHAR(250),
    ID_ONG INT, --FK
    DATA_DOACAO DATETIME,
	
    FOREIGN KEY (ID_DOADOR) REFERENCES DOADOR(ID_DOADOR),
    FOREIGN KEY (ID_FORMA_PAGAMENTO) REFERENCES FORMAS_PAGAMENTO(ID_FORMA_PAGAMENTO),
    FOREIGN KEY (ID_ONG) REFERENCES ONG(ID_ONG)
);

CREATE TABLE ENDERECO (
    ID_ENDERECO INT IDENTITY PRIMARY KEY,
    ID_ONG INT, --FK
    RUA VARCHAR(250),
    BAIRRO VARCHAR(250),
    CEP CHAR(8),
    NUMERO INT,
    COMPLEMENTO VARCHAR(250),
    CIDADE VARCHAR(250),
    UF CHAR(2), --2 caracteres
    DATA_CADASTRO DATETIME,

    FOREIGN KEY (ID_ONG) REFERENCES ONG(ID_ONG)
);